### ISSUE TITLE
listener state: Not listening [not supported] on Windows 10 home x64 2004 update   10.0.19041.84

### ISSUE THREAD

**Issue by robbak** [stascorp/rdpwrap#1081]
listener state: Not listening [not supported] on Windows 10 home x64 2004 update   10.0.19041.84

_Originally posted by @psndna88 in https://github.com/stascorp/rdpwrap/issues/999#issuecomment-640523281_

You replied in someone else's thread - please don't do that when asking for help. Create your own new thread.

You will also have to provide more information - what rdpwrap.ini file are you using? What method did you use to install? What have you already tried?

**Comment by Cuile** [comment]
新的ini文件可以用这个，亲测可用[update for 10.0.19041.84 and 10.0.19635.1 x64](https://github.com/Octanium91/rdpwrap/commit/e67ecce0b593735fd28fcd419b3369b426c8f36f)

**Comment by ANKUSHJAIN91** [comment]
Please update on this 
listener state: Not listening [not supported] on Windows 10 home x64 2004 update 10.0.19041.84

**Comment by infiniti25** [comment]
Does anyone have a fix?
I tried the updated ini file, I've tried the autoupdater from another repository and I've ensured I've added the rfxvmt.dll version 10.0.15063.0 to system32 folder and I still have not listening and [not supported].
Spent around 5 hours last night reading through the issues on this and a few other mirror repos but couldn't get any further.

I'm even considering following the video guide to try and work out what the offsets are myself...but I doubt that will end well for me.

**Comment by affinityv** [comment]
If it's not listening, then I would think it /might/ be "Windows Defender" or an AV product.  Make sure you have exceptions for the "C:\Program Files\RDP Wrapper" directory.  Then uninstall and re-install RDPWrapper with `RDPWInst -u` and `RDPWInst -i` -- this is so as not to clobber the new INI file that you must have in the "C:\Program Files\RDP Wrapper" directory.  If the new INI file isn't there, then put it there and do `RDPWInst -r`

All of this with elevated admin user of course.

**Comment by infiniti25** [comment]
@affinityv thanks for the response.
It seems that my Windows Defender/Microsoft Defender is in an error state. I disabled it when I had my old install and I recently updated to 2004. I can't enable Defender nor can I add an excluded folder. I can however run a manual scan. So I obviously have an issue to fix there. But I'd assume since it's broken it wouldn't be able to interfere?

**Comment by TheArgentinian** [comment]
has anyone found a fix?

**Comment by robbak** [comment]
Yes, this one is fixed. Use the .ini file in #1105 . Download it from the 'changed files' tab.

**Comment by infiniti25** [comment]
Thank you all, especially to other users hosting mirrors/archives of this app and creating additional supporting content and the people providing assistance in these Issues.
Would just like to say I managed to solve it after spending about 15 hours over a week trying.
I managed to get Windows Defender fixed so it was working and add the exclusion for the RDPWrapper folder but that still didn't solve it.
This issue was on Windows 10 home x64 update 2004 10.0.19041.84
[rdpwrap_for_10.0.19041.84_fix_files.zip](https://github.com/stascorp/rdpwrap/files/4897820/rdpwrap_for_10.0.19041.84_fix_files.zip)
.
I opened Powershell  as Administrator.
I used RDPWInst -u -r to uninstall RDPWrapper and to restart Terminal Services.
I rebooted the machine.
I obtained the autoupdate.bat file from this repository and the autoupdater script from https://github.com/asmtron/rdpwrap/tree/master/bin.
I placed them all in the same folder.
I opened Powershell as Administrator.
I changed directory to the downloaded files.
I ran autoupdate.bat script.
I checked the output at the end to see whether there were any errors. I believe I had errors on the first run.
I ran RDPWInst -u -r again to uninstall RDPWrapper and to restart Terminal Services.
I rebooted the machine.
I created termServicesFix.bat which includes permissions fixes mentioned in one of the support tickets I don't have the link for.
I changed the Computer Name and User Name in that batch file on the first two lines (then saved)- IMPORTANT!
I right clicked the termServicesFix.bat and selected Run as Administrator.
I opened Powershell  as Administrator.
I changed directory to the downloaded files.
I ran autoupdate.bat script and there were no errors in the ouput at the end of the script.
I ran RDPConf.exe and everything looked like it should.
![image](https://user-images.githubusercontent.com/46777481/87060310-47e2f200-c202-11ea-9192-35f9233248c6.png)

I would just say that if this doesn't fix it for you, look at getting GPedit.msc for Windows 10 Home and checking the remote desktop options in there. There is also an RDP.reg file available somewhere to put the registry entries from Windows 10 Pro into Windows 10 Home which might be needed prior to running GPedit.msc.

You can also find a replacement RDPcheck.exe without the error by looking through some of the issues, but I don't remember the repository.

Hope this helps others with the same issue.

**Comment by FMYY** [comment]
> 新的ini文件可以用这个，亲测可用[update for 10.0.19041.84 and 10.0.19635.1 x64](https://github.com/Octanium91/rdpwrap/commit/e67ecce0b593735fd28fcd419b3369b426c8f36f)

感谢，虽然不知道怎么下载文件，但是我复制了您所有的代码，贴入自己的ini就生效了，再次感谢

**Comment by Noddy1970** [comment]
I installed RdpWrapper on W10 1909 and W10 20H2 .
It works all fine with these files but you have to re install all if Windows version change.
[RDPWrap-v1.6.2.zip](https://github.com/stascorp/rdpwrap/files/5541218/RDPWrap-v1.6.2.zip)
You have to follow the usual procedure for installation ; but the file which is very important is rdpwrap.ini (194ko).
