### ISSUE TITLE
RDP Wrapper conf. 10.0.18362.836 is full supported, but two different login user error.

### ISSUE THREAD

**Issue by surat** [stascorp/rdpwrap#1158]
![RDP error](https://user-images.githubusercontent.com/70740335/92203303-6da51400-ee9e-11ea-9e0f-85cfc2e6edff.jpg)

**Comment by surat** [comment]
![Capture](https://user-images.githubusercontent.com/70740335/92203463-d7252280-ee9e-11ea-9b39-28fe6faa0f47.PNG)

**Comment by surat** [comment]
OS windows 10 1909

**Comment by robbak** [comment]
This is either caused by a group policy set on your computer, or a lack of
graphics resources to support multiple users.

Check out these suggestions, or search for others. This is most likely not
an issue with rdpwrapper, but with the rdp configuration..

https://www.serverwatch.com/server-tutorials/multiple-remote-desktop-connections-on-windows-server-2016-and-windows-server-2012.html

**Comment by surat** [comment]
Thanks,
Edited group policy.
Check multiple Desktop different Windows 10 OS, but same error. 
Try to 10-12 desktop, but this same error.

**Comment by Hiteshkalsariya** [comment]
Multiplay users can not login after installing RDP, not solutions for this RDP, just time pass.

**Comment by sithbass** [comment]
Hey, Surat. Did you get to fix this? Getting the same problem here

**Comment by sebaxakerhtc** [comment]
Applicable to https://github.com/stascorp/rdpwrap/issues/1083
