### ISSUE TITLE
Leaving remote session unlocked

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#134]
I am trying to use my windows 10 Home PC for inhome streaming (steam). For that I have to be able to disconnect from a remote session, without locking the session. The solution I've found on the web suggests using `tscon.exe %sessionname% /dest:console`, but tscon.exe doesn't exist. I have read in another issue that including tscon.exe in the installer is not possible, so I am asking for any workarounds.

**Comment by binarymaster** [comment]
If you need to leave session active (e.g. connected to some display — Console or RDP-Tcp#xx), you may create an `.rdp` file with Remote Desktop Client to connect to your session (or create if not exist).

Then add this file to scheduled tasks, and start the task. Remote Desktop Client will run in background, connected to your destination session.

**Comment by johanneskonst** [comment]
@PsychoTheHedgehog I'm not quite shure why you'd need to remote connect to the W10 PC when all you want is to stream Steam to another computer (or Steam Link), but maybe describing my setup will help you.

I've got a game PC with one local account set to automatically login which runs Steam (also auto-login) so that basically when I boot that PC I've got Steam available on my network within a few minutes. 
If I need to make changes using that account I remote connect, make my changes and then hit the Reboot shortcut on my desktop so that after a while I've got Steam available again ready for any streaming. No need to keep remote sessions unlocked et al.

The Reboot shortcut is basically:
1. right-click desktop
2. click new -> shortcut
3. enter the text "%windir%\system32\shutdown.exe -r -t 0" (without quotes) and hit next
4. give it a nice name and hit enter
5. optionally right-click shortcut, properties, and select a different icon

I've got a similar one for Shutdown so that I can power off that PC remotely (shutdown.exe -s -t 0)

Hope this helps.

**Comment by JakeStevenson** [comment]
Rebooting the entire machine won't work for everyone.  For mine, the bootloader will go to another operating system by default, so rebooting remotely would leave me worse off.

**Comment by DavitHin** [comment]
tscon.exe doesn't come with Windows Home Edition but the solution is easy just copy anywhere from Windows pro and paste it in %windir%system32 Work like charm

**Comment by sebaxakerhtc** [comment]
Closed as solved. If not - reopen it.
