### ISSUE TITLE
This is a note all who own Win 10 Pro 20H2. 

### ISSUE THREAD

**Issue by mlvbible** [stascorp/rdpwrap#1354]
The Evil Microsoft has made it impossible to replace the termserv.dll file in C:\Windows\system32 
So RDP Wrapper is dead in 20H2, until someone has a way to fix this issue. 

I tried Safe Mode. I put the hard drive in a different computer also in Safe Mode. 

Xcopy & File Explorer will not allow the file to be overwritten with the version used in RDP Wrapper.

**Comment by LiamKarlMitchell** [comment]
Microsoft already made commands to take ownership of a file.
But there could be other protection enabled? DEP protection?

Have you tried this?

Before you edit the termsrv.dll file, you have to become its owner and give the Administrators group the full permissions to it. The easiest way to do this is from the command prompt. To change the file owner from TrustedInstaller to a local administrators group use the command:

Now grant the local administrators group Full Control permission on the termsrv.dll file:

http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/
```
takeown /F c:\Windows\System32\termsrv.dll /A
icacls c:\Windows\System32\termsrv.dll /grant Administrators:F
```

I thought that RDPWrap changes it in memory however? not by patching the file on disk.

**Comment by mlvbible** [comment]
I was able to copy the old termsrv.dll over the top of the current 20h2 file and no remote desktop anything works now.

**Comment by mlvbible** [comment]
The RDP Service will not stop or start. Moving it to Manual, still gave me no good results.

**Comment by powerLambda** [comment]
dam it, I just upgraded to 20H2 five minutes ago... I should check the post before upgrade!

**Comment by powerLambda** [comment]
Thanks Microsoft provides RollBack to last version!  REFUSE to UPGRADE!

**Comment by LiamKarlMitchell** [comment]
![image](https://user-images.githubusercontent.com/1968109/112299011-40b23480-8cfc-11eb-8226-86c46d371915.png)
![image](https://user-images.githubusercontent.com/1968109/112299128-60495d00-8cfc-11eb-8435-ce9cd2b9d92e.png)
Works fine.

**Comment by bharat-mukheja** [comment]
@LiamKarlMitchell it's not working for me. Windows 20H2, new install of RDPWrap, but Listener State is still showing "not supported"

**Comment by LiamKarlMitchell** [comment]
Use the auto updater bat?
https://github.com/stascorp/rdpwrap/pull/1160

You will need to restore the original official dll file.

**Comment by botka4aet** [comment]
Doesn't work even after updater bat
```
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Checking for updates...
[*] Current update date: 2018.10.10
[*] Latest update date:  2018.10.10
[*] Everything is up to date.
```
![image](https://user-images.githubusercontent.com/11385249/112481810-73097380-8d88-11eb-90ae-27adaa456182.png)

**Comment by DeviousFusion** [comment]
This is what I got:
![rdp](https://user-images.githubusercontent.com/2919871/112568866-2a19e500-8db1-11eb-9c35-dce3af993ba8.PNG)

I do have an optional update waiting. So that might be whats killing ya'lls installs. Its KB5001649. Try removing that and see if it helps.

**Comment by botka4aet** [comment]
About KB5001649 - i'm not installing it also, only have mes about it
`Windows 10 Pro

20H2

‎24.‎02.‎2021

19042.867

Windows Feature Experience Pack 120.2212.551.0
`

**Comment by Yanitwei** [comment]
![image](https://user-images.githubusercontent.com/81416060/112618075-3482c000-8e3f-11eb-874a-9b38e9849e10.png)

+1 Optional update KB5001649 isn't installed, still unsupported for 20H2.

I haven't patched anything on my own yet, but I'm thinking to give it a try. If anybody succeeded please reach out guys.

![image](https://user-images.githubusercontent.com/81416060/112624653-584a0400-8e47-11eb-864c-66eca1c2a6b5.png)

Edit: I managed to make it work! I Patched Termsrv using instructions in [this](woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/) article. Simply I found similar to older win10 builds hex string "39 81 3C 06 00 . . ." in original termsrv.dll and replaced it with new one "B8 00 01 00 00 89 81 38 06 00 00 90" 
Used [this](https://hexed.it/) editor

And in order to be able to replace patched termsrv with the one in system32, I took ownership from TrustedInstaller using this commands (in cmd with admin privileges.) 

```
takeown /F c:\Windows\System32\termsrv.dll /A
icacls C:\Windows\System32\termsrv.dll /grant Administrators:F
```

I stopped TermService before replacing the file and started it again after the replacement using this commands.
```
net stop TermService
Y
net start TermService
```

and here you go guys [patched ](https://github.com/stascorp/rdpwrap/files/6211464/Patched.termsrv.Win.10.Pro.x64.20H2_v2.Buiild.19042.867.zip)termsrv.dll for Windows 10 20H2_v2 build 19042.867.

This should help to the ones looking for solution!

**Comment by mlvbible** [comment]
I had a fully patched 20H2 and then followed: 

https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

Mine is working. But this computer is a server for an Access DB, so I killed the internet access to it.

**Comment by dterp-69** [comment]
THANK YOU Yanitwei & mlvbible for the answers I needed!!!!

**Comment by gjuecat** [comment]
does anybody have an update for 21H2 19044.1288? this version is not supported at the moment

**Comment by sebaxakerhtc** [comment]
> The Evil Microsoft has made it impossible to replace the termserv.dll file in C:\Windows\system32

Not an rdpwrapper issue
