### ISSUE TITLE
how to change resolution ?

### ISSUE THREAD

**Issue by jeanroukas** [stascorp/rdpwrap#139]
I can't find a way to change the resolution of the window. Do i miss something ?

**Comment by binarymaster** [comment]
Is it about `RDPCheck`? It doesn't allow to change resolution since it's just a testing application.

Microsoft Remote Desktop Client (`mstsc.exe`) allows to change resolution, you need to use it.

**Comment by jeanroukas** [comment]
oh thanks. Perhaps you can write-it on the read-me file. :)

**Comment by binarymaster** [comment]
Allright, done!

**Comment by binarymaster** [comment]
See `README.md`, I mentioned correct addresses for connection.

**Comment by jeanroukas** [comment]
thanks :)

**Comment by alexchandel** [comment]
Note for those future user:

If you're trying to use RDPCheck to connect to your own machine from the console session, and mstsc doesn't seem to support connecting to the localhost, either via `127.0.0.1` or the hostname (`mstsc /v:127.0.0.1` returns the mysterious error "Your computer could not connect to another console session on the remote computer because you already have a console session in progress."), then try `mstsc /v:127.0.0.2`. That worked for me.
