### ISSUE TITLE
not working on 21h1 version 10.0.19041.1081

### ISSUE THREAD

**Issue by a6004tr** [stascorp/rdpwrap#1454]
if you install servicing stack update from microsoft updtae it won't work anymore

**Comment by sk-lau** [comment]
Hi,

Have you tried this ini file ?
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by ghost** [comment]
Worked for me. Thanks

**Comment by ghost** [comment]
Removed the previous autoupdater.bat and helper and redownloaded from the link below.
https://github.com/stascorp/rdpwrap/pull/1160

Fixed it for me on 21H1.

**Comment by aogg** [comment]
+1

**Comment by perjune** [comment]
Anybody can help me to post the offsets in rdpwrap.ini for this version? Because I can't access the link as posted above. I would appreciate it.

**Comment by bunyrabitt** [comment]
Hi All,

I installed as per instructions with the autoupdater.bat and helper. I had all green but when I ran the RDPCheck the screen I got did not show any users. I then changed the setting in Remote desktop services to local system account instead of this account and in order to do so I stopped the service. it did not stop it just said "stopping", I then restarted the computer and since then everything is green as per below except the Listener State is not listening. I have since restarted the computer and installed an update to the one in this thread.  Can anyone suggest any possible fixes or do I need to uninstall everything and go back and start from scratch. I can no longer select "this account" in the remote desktop services properties.

![rp wrapper config](https://user-images.githubusercontent.com/87064288/124727950-86fd6d80-df52-11eb-95c6-5e9b6206ae68.PNG)
![remote desktop services](https://user-images.githubusercontent.com/87064288/124728059-9e3c5b00-df52-11eb-8b28-684834bbc599.PNG) 

any help or direction appreciated. 

Cheers.

**Comment by bunyrabitt** [comment]
uninstalled everything and started from scratch 
![uninstall](https://user-images.githubusercontent.com/87064288/124834231-bea3fe00-dfc2-11eb-92f6-7272358834f5.PNG)
there are a couple of errors in the uninstall. tried a different configuration file but still getting fully supported but not listening. I am thinking the problem could be in the termsrv.dll file. I have been following a process to install and do not have knowledge about how all the files work so troubleshooting is a stab in the dark.

Again any help appreciated.

Cheers.

**Comment by bunyrabitt** [comment]
Finally got it working the issue was in the remote desktop services properties. this account had to be selected. I entered Network Services and my login account pass. when I applied it automatically populated a password. I then stopped and started the termservices and all working. Hopefully this can help another battler out there.

Cheers.

![rds](https://user-images.githubusercontent.com/87064288/124836817-f9a83080-dfc6-11eb-93ba-2b1aa3d9ec96.PNG)

![fully supported](https://user-images.githubusercontent.com/87064288/124837126-9b2f8200-dfc7-11eb-90aa-b21fecf7ab46.PNG)

**Comment by tipstar23** [comment]
Anyone else?

I tried @bunyrabitt but no success?

**Comment by tipstar23** [comment]
I'm running
![Screenshot 2021-07-08 110351](https://user-images.githubusercontent.com/49510410/124846477-3d596500-dfdc-11eb-9b2a-44b6d9b9ebda.png)
 this

**Comment by tipstar23** [comment]
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

This worked for me.

**Comment by gaborboti** [comment]
> Hi,
> 
> Have you tried this ini file ?
> https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

Worked for me. Thank you.

**Comment by everdominguez** [comment]
> if you install servicing stack update from microsoft updtae it won't work anymore

¿How can I remove the update?

**Comment by everdominguez** [comment]
I can use the RDP with 1 user, anybody knows how does work with multiple users?

**Comment by AdamTurock** [comment]
I'm using 21H1 Enterprise and still not working.  I tried a fresh install and updating the latest RDPwrap.ini.  Is a fix being worked on for the Enterprise version?

**Comment by everdominguez** [comment]
> I'm using 21H1 Enterprise and still not working. I tried a fresh install and updating the latest RDPwrap.ini. Is a fix being worked on for the Enterprise version?

Do you try to start the rdp or multiple users?

**Comment by AdamTurock** [comment]
Yes, I tried RDPcheck and get error 0x4.  Rebooting the computer will cause a RPC error at login and will infinite loop the login.  You will need to stop the 'TermServices' service to be able to login.  Tried several options on RDPconfig.

**Comment by b2never** [comment]
> 
> 
> Hi,
> 
> Have you tried this ini file ?
> https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

this worked great for 10.0.19041.1081 21h1 x64 home edition
i did RDPWInst.exe -r and net start termservice after replacing ini file
thanks alot

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
