### ISSUE TITLE
RDP Wrapper stopped working with 19042.1110

### ISSUE THREAD

**Issue by regissg** [stascorp/rdpwrap#1472]
Does any one has the proper rdpwrap.ini file for that version?

**Comment by alexlegui** [comment]
I have the same ver of w 10 (windows 10 20h2 "19042.1110"). The RDP ver isn't works (rdpwrap)

I apreciated your support.

**Comment by STSebas** [comment]
Good afternoon, I also have this same version of windows, it was updated a few days ago and the rdp is not working, it does not support it

**Comment by wujun-cse** [comment]
Need helps too.

**Comment by dancingniki** [comment]
I also have the same issue with 20H2 19042.1110.
How can I learn to do it myself?

**Comment by B-CCCPcekca-HET** [comment]
wait fix this problem too.

**Comment by DougShaner** [comment]
I'm having the same trouble.  Commenting here in hopes of being notified when the fix comes out.

**Comment by DougShaner** [comment]
This fixed it for me:  https://github.com/stascorp/rdpwrap/issues/1466

**Comment by flybeye** [comment]
for Installing, I would use asmtron's version of the autoupdate.bat, install.bat, uninstall,bat, etc.
https://github.com/asmtron/rdpwrap/tree/master/bin

run the files as Administrator

for updating for working on 19042.1110 (windows version)... i did the following:

mine is working with the one from asmtron fork
https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini

Might need to stop Term Services: net stop TermService
update the ini file from above, into your RDPWrapper directory (C:\Program Files\RDPWrapper)
then restart Term Services: net start TermService

or if your RDP wrapper is from asmtron Github, then you can run the autoupdate.bat as Administrator since asmtron has already
updated his repo.

**Comment by wujun-cse** [comment]
> for Installing, I would use asmtron's version of the autoupdate.bat, install.bat, uninstall,bat, etc.
> https://github.com/asmtron/rdpwrap/tree/master/bin
> 
> run the files as Administrator
> 
> for updating for working on 19042.1110 (windows version)... i did the following:
> 
> mine is working with the one from asmtron fork
> https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini
> 
> Might need to stop Term Services: net stop TermService
> update the ini file from above, into your RDPWrapper directory (C:\Program Files\RDPWrapper)
> then restart Term Services: net start TermService
> 
> or if your RDP wrapper is from asmtron Github, then you can run the autoupdate.bat as Administrator since asmtron has already
> updated his repo.

It works, thanks!

**Comment by maxxalin2000** [comment]
Hello, i replaced rdpwrap.ini from asmtron fork link but still not working, can' connect more than 1 user. Any ideas?

Windows Ver:   [Version 10.0.19043.1110]

Thanks!

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
