### ISSUE TITLE
RDP wrapper not supported on windows 10 version 21H1(19043.1110)

### ISSUE THREAD

**Issue by john1089** [stascorp/rdpwrap#1475]
The RDP Wrapper showed up to be unsupported even though I did everything that i can.
here's the dll.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6838079/termsrv.zip)

**Comment by TheGooodDoctor** [comment]
Same here. Anyone who can point to an update that works with 1110?

**Comment by flybeye** [comment]
I have the 21H1 with 19043.1110 and mine is working with the one from asmtron fork
https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini
![image](https://user-images.githubusercontent.com/22753145/126694943-93539525-1443-4b37-b8b1-8686c2a5792a.png)

Might need to stop Term Services: net stop TermService
update the ini file from above, into your RDPWrapper directory (C:\Program Files\RDPWrapper)
then restart Term Services: net start TermService

or if your RDP wrapper is from asmtron Github, then you can run the autoupdate.bat as Administrator since asmtron has already
updated his repo.

**Comment by TheGooodDoctor** [comment]
Thank you flybeye. It worked and we're back in business. Thank you. Thank you.

**Comment by sneakyrussian** [comment]
Thanks @flybeye, weirdly, though everything appears to be ok and running, I still can only get a single RDP session to my Win10 machine (tried with two individual users)

![image](https://user-images.githubusercontent.com/63844024/126895576-f0dc1512-f8c9-469f-8c5a-42e0ea19e7bb.png)

Any ideas would be much appreciated

**Comment by bartlettD** [comment]
Saw this issue and tried out Asmtron's fork but it didn't work either. I get all green but when I connect I get the blank login screen from #1469. Do we need new offsets for this version?

**Comment by TheGooodDoctor** [comment]
I could be wrong, and I generally am, but I suffered the blank log in screen as well. But that problem (for me) related to a Windows upgrade problem. Microsoft kept telling me to update windows, but that did not solve the blank screen at all. Updating  display drivers did not fix the problem. I couldn't wait any longer so I had to take some drastic measures, like new hardware and reformatting. But all that may not be your problem. Anyway, all working for me now. All the best for yourself.

**Comment by ghost** [comment]
You can fix by this way https://youtu.be/aeNe_UUBgys

**Comment by sk-lau** [comment]
I have applied also the rdpwrap.ini from Amstron but it did not work

I get the following error when I try to connect remotely

![Capture](https://user-images.githubusercontent.com/30503455/127745091-1bc61402-e2de-42c2-a8f9-a10d84183b2b.PNG)

The weird thing is even after i have uninstalled RDPWrap, my remote desktop still give the same error

Any ideas guys?

-----------------------------------------------------------------------------------

Turns out the file below does solve the RDP issue. Mine is more of a Windows settings problem

**Comment by pnz1024mb** [comment]
Works on 10 21H1 19043.1110 https://youtu.be/aeNe_UUBgys
[rdpwrap_10.0.19043.1110.zip](https://github.com/stascorp/rdpwrap/files/6911783/rdpwrap_10.0.19043.1110.zip)

**Comment by itsleehon** [comment]
> Works on 10 21H1 19043.1110 https://youtu.be/aeNe_UUBgys
> [rdpwrap_10.0.19043.1110.zip](https://github.com/stascorp/rdpwrap/files/6911783/rdpwrap_10.0.19043.1110.zip)

thanks very much!

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1447
