### ISSUE TITLE
Request for a release

### ISSUE THREAD

**Issue by Mannshoch** [stascorp/rdpwrap#1492]
The current software release is still from 2017.
Please create a new release

**Comment by affinityv** [comment]
There is zero need for a new release, the project is pretty much perfect; you only to update the INI file only and that is being updated by others (including myself).

**Comment by stuaxo** [comment]
It would be good if there was a new release with the ini updates (or just update the docs to reflect that it's needed)

**Comment by jzablot** [comment]
> There is zero need for a new release, the project is pretty much perfect; you only to update the INI file only and that is being updated by others (including myself).

My constructive criticism for this project would be a more convenient crowd sourced way for everyone to stay up to date with necessary ini changes for each Windows update.

The fact that rdpwrap is flexible enough to deal with Windows updates without rdpwrap code changes is great; however it seems very cumbersome to have to dig through issue reports or otherwise google the right new ini settings after every Windows update that breaks previous ini setting.

Don't get me wrong -- I really appreciate this project; I just feel it could be even better if we could come up with a better way to contribute and share ini updates. Or perhaps there is some good way and many, including myself, are just not aware?

**Comment by affinityv** [comment]
All good with the comments, but I'm just as happy for no version change whatsoever as a release, perhaps just a README update is all that is required WITHOUT an actual release.

**Comment by sebaxakerhtc** [comment]
> The current software release is still from 2017. Please create a new release

It still works
