### ISSUE TITLE
rdwap.ini for 10.0.19041.1202

### ISSUE THREAD

**Issue by virgilioribeiro** [stascorp/rdpwrap#1508]
Need rdwrap.ini file for 10.0.19041.1202

tanks

**Comment by affinityv** [comment]
[termsrv--2021-09-02a--10.0.19041.1202.dll.zip](https://github.com/stascorp/rdpwrap/files/7099051/termsrv--2021-09-02a--10.0.19041.1202.dll.zip)
64 bit version
@sebaxakerhtc
NB: the "zip" file was created as ".7z" and renamed so it could be attached here, let me know if there is any problem extracting it.

**Comment by virgilioribeiro** [comment]
thank you, but will it be possible to send me the rdwrap.ini file first?

**Comment by affinityv** [comment]
> thank you, but will it be possible to send me the rdwrap.ini file first?

Once the dll is used to create the INI section, by someone -- @sebaxherhtc can do this with his auto-generation, then the INI files will be updated, including mine [here](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)

Usually each new dll will have new values and playing around with guesses is a bad way to go.

**Comment by sebaxakerhtc** [comment]
> 
> 
> [termsrv--2021-09-02a--10.0.19041.1202.dll.zip](https://github.com/stascorp/rdpwrap/files/7099051/termsrv--2021-09-02a--10.0.19041.1202.dll.zip)
> 64 bit version
> @sebaxakerhtc
> NB: the "zip" file was created as ".7z" and renamed so it could be attached here, let me know if there is any problem extracting it.

Values added. There is no difference with 1904x.1200

**Comment by virgilioribeiro** [comment]
thank you, work !!!

**Comment by LING9911** [comment]
Excuse me, how can I use rdwap.ini file?

**Comment by affinityv** [comment]
> Excuse me, how can I use rdwap.ini file?

Do the normal install, if you haven't done that already.
Copy in the new [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini), replacing the one in "C:\Program Files\RDP Wrapper"
Restart RDPWrap with `RDPWInst.exe -r` as an admin user.

**Comment by LING9911** [comment]
Thank you very much!



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 3, 2021 20:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [stascorp/rdpwrap] rdwap.ini for 10.0.19041.1202 (#1508)




  
Excuse me, how can I use rdwap.ini file?
  
Do the normal install, if you haven't done that already.
 Copy in the new INI, replacing the one in "C:\Program Files\RDP Wrapper"
 Restart RDPWrap with RDPWInst.exe -r as an admin user.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by panchinet** [comment]
Thank you very much.
