### ISSUE TITLE
Windows Defender PUA:Win32/Presenoker

### ISSUE THREAD

**Issue by filippobottega** [stascorp/rdpwrap#1540]
Hello,
  when I download the installer Windows Defender found that it's a PUA, Potentially Unwanted Application.

![image](https://user-images.githubusercontent.com/2587684/134759182-fd164e4f-457b-4e1d-8cfc-27c9859358fd.png)

Do the wrapper use Presenoker component?

  Thank you.

**Comment by sashaqwert** [comment]
Windows Defender (real name Microsoft Defender) considers this software to be potentially unwanted because it allows you to bypass the software limitations of the Windows operating system.

Bypassing software restrictions is prohibited by the license agreement.

The Windows 10/11 license agreement explicitly states that the license is issued for the use of one copy of the OS on one licensed device **by one person at a time**.
An exception is made for the remote assistant and programs that work similarly to him (i.e., connection to the same session is allowed by a license)

**Comment by mabaega** [comment]
Better use protable zip version
