### ISSUE TITLE
Desktop wont show.. 10.0.19043

### ISSUE THREAD

**Issue by Nuriko93** [stascorp/rdpwrap#1588]
Hey guys i installed rd wrapper and all is green but i cant connect, can you help me?

![image](https://user-images.githubusercontent.com/93793353/140567021-7f2c5da6-7538-4d3e-988d-6c20606ee587.png)

![image](https://user-images.githubusercontent.com/93793353/140567077-7035ad8e-d50f-4d64-b84a-13f2070a0350.png)

**Comment by LookingforRDPhelp** [comment]
thats what i had and my rdp still isnt working and have the same problem

**Comment by zekecarter** [comment]
[VIDEO](https://youtu.be/hH4iaRAFALE) you need to uninstall and reinstall the rdpwrapper program. watch the video, unfortunately is in Spanish but the guide works. that happened to me before and it was because I updated the .ini file without stopping the remote desktop service. I hope it works for you

**Comment by sebaxakerhtc** [comment]
Acceptable to https://github.com/stascorp/rdpwrap/issues/1509
