### ISSUE TITLE
gpu hardware encoding h.264 avc 444 more disqualified than software cpu encoding

### ISSUE THREAD

**Issue by andreaordonselli** [stascorp/rdpwrap#1646]
Hello, I have been using wrapper for several months with RDP configured for gpu hardware encoding with the two settings activated h.264 avc444 in "remote session environment" and everything has always gone perfectly.
With the latest windows update and subsequent wrapper autoupdate I had to disable hardware encoding because the RDP images were more disqualified than the software encoding, however with the software encoding, fully loaded on the CPU, the system is very slow.
Are there any solutions or should I wait for a new windows/wrapper update?
PS: I use the same PCs, they do not change, I have not installed software but only made windows updates; the server is win10enterprise, the client win10home.
Thanks.

**Comment by sashaqwert** [comment]
> Are there any solutions or should I wait for a new windows/wrapper update?

RDP Wrapper is a wrapper over termsrv.dll that runs it with different parameters.
The problem is most likely in Windows.
You can check this by uninstalling the RDP Wrapper and going to the [Enterprise multi-session (ServerRdsh) edition](https://github.com/stascorp/rdpwrap/issues/1478#issuecomment-886222080).

In the description of the group policy for hardware rendering, there is a warning about a graphical breakdown.

**Comment by sebaxakerhtc** [comment]
Not an rdpwrapper issue, but M$
