### ISSUE TITLE
In Windows Server 2019 not working 

### ISSUE THREAD

**Issue by jeinjhon2022** [stascorp/rdpwrap#1814]
![image](https://user-images.githubusercontent.com/103796488/163656290-fb83dc75-89d5-445f-9c45-3e0564df662d.png)
![image](https://user-images.githubusercontent.com/103796488/163656307-aa68b6a2-b91d-4772-be65-470593181704.png)

**Comment by sebaxakerhtc** [comment]
RDPWrapper is not installed. Maybe your antivirus delete necessary files

**Comment by xenan33** [comment]
> RDPWrapper is not installed. Maybe your antivirus delete necessary files

What can we do? I don't see anymore files under quarantine

**Comment by xenan33** [comment]
> > RDPWrapper is not installed. Maybe your antivirus delete necessary files
> 
> What can we do? I don't see anymore files under quarantine

nvm, I was able to fix the error by doing a in-place upgrade on the computer which had fixed the registry

**Comment by sebaxakerhtc** [comment]
Not an RDPWrapper issue but AntiVirus software

**Comment by accnetdev** [comment]
Hi,
I use RDP Wrapper (last sebaxakerhtc version) a very handy and reliable tool.

Today I noticed there is no longer the termservice on this PC under Windows 11.
I'm on Microsoft Windows [version 10.0.22631.4602] my Antivirus ESET EndPoint Security 12.0.2038.0 is OK (nothing in history related to TermService or RDPWrapper) but I found several "Incomplete update" in Defender history related to the TermService.

I suppose that Defender has deleted my TermService after several detections of HackTool:Win32/RemoteAdmin!MSR, it's new because before dec 16 2024 there was no problem with this kind of detections.

My problem is : how to restore my TermService that has disapeared?
My OS is Windows 11 Pro 23H2 (18/11/2022 - 22631.4602) can you give the registry item to add/restore for Win11?

Thanks for your help.

**Comment by accnetdev** [comment]
To help the community the reg (for Win10) in this topic is OK for Windows 11 (upto my actual version).
I applied/import the reg + reboot the TermService is now in services.msc.
I reinstalled seba/rdpwrapper and all is OK now.
Be careful Defender is probably the cause even if you use another antimalware like me ESET as the main AV...
