### ISSUE TITLE
rdpwrap 1682,termsrv 1741?

### ISSUE THREAD

**Issue by 0Zaporozhec0** [stascorp/rdpwrap#1941]
Please help, not wrk rdp with update july 2022, in screen is 1682 version, but in folder c: windows termsrv.dll - 1741.

ok, i put rdpwrap.ini in folder program files, when 1741 correct.

Users come in, all ok. But in programm rdpwrap is 1682 full supported! Where i do correct a mistake?

![121212](https://user-images.githubusercontent.com/106913100/181300930-bf58fa60-071e-45d2-b9ca-d1bc5f255803.jpeg)

all work! but this mistake is not right...

**Comment by 0Zaporozhec0** [comment]
and i restart termsrv service too)))) whats happened?

**Comment by sashaqwert** [comment]
Please, disable Autoupdate.bat (if you using this script). Them execute `sfc /scannow` and reboot.

Please, send RDPConf screenshot after this.

**Comment by 0Zaporozhec0** [comment]
i do it, but not happened

**Comment by sashaqwert** [comment]
1741 is correct version (issue https://github.com/stascorp/rdpwrap/issues/1881)

If RDPConf shows a version other than the one in System32, then something is wrong with your system.

If you want to sort out your problem, it's better to write to Telegram chat https://t.me/rdpwrap (there's more chance of getting an answer).

Since most likely the problem is not with the RDP Wrapper, but with your system, this issue will be closed.
