### ISSUE TITLE
Is it necessary to use rdpwrap on Windows Server 2022 for multiple remote sessions?

### ISSUE THREAD

**Issue by 1337yokese** [stascorp/rdpwrap#1945]
Hi everyone!

I use rdpwrap on windows 10, but I want to move to Win Server 2022. Is it necessary to use rdpwrap on Win Server 2022 or would simply increasing the number of connections work the same as Win 10 with rdpwrap?

Best regards!

**Comment by sashaqwert** [comment]
> would simply increasing the number of connections work the same as Win 10 with rdpwrap?

RDP Wrapper will work on Windows Server only if the [RDS](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-roles) role is not installed. With the RDS role installed, for RDP Wrapper to work, you will always have to write "/admin" when connecting.

Without RDP Wrapper and RDS role, 2 simultaneous connections are available.

With the RDS role installed, but without the RDP Wrapper, an unlimited number of connections are available for 120 days from the moment the RDS role is installed. At the same time, only 2 sessions with the "/admin" argument are available.
The 120-day RDS trial period can be reset: https://www.virtualizationhowto.com/2020/10/reset-120-day-rds-grace-period-on-2016-and-2019/
Together, you can license RDS using a licensing server.

Thus, the RDP Wrapper on Windows Server removes the limit on the number of administration sessions. The administrative session counter takes into account the console session.

---------------

This issue will be closed because the answer to this question has been given many times. However, this does not prevent us from asking clarifying questions here.

**Comment by nattlip** [comment]
is not the way to use rdp wrapper with a server to use windows 10 or maybe eleven in the same domain and install rdp wrapper on the windows 10 ""child""

**Comment by nattlip** [comment]
is not the way to use rdp wrapper with a server to use windows 10 or maybe eleven in the same domain and install rdp wrapper on the windows 10 ""child""

**Comment by sashaqwert** [comment]
@nattlip RDP Wrapper can be easily installed on any Windows 10/11.
If you have a dedicated remote desktop server (or VM), then you can consider Windows 10/11 Enterprise multi-session.

<details>
<summary>You can get ISO via UUP dump</summary>

https://uupdump.net/

![изображение](https://user-images.githubusercontent.com/24974508/182018833-ec7f832f-ca2a-454e-b8f0-3ba09bccac54.png)

</details>

**Comment by nattlip** [comment]
@sashaqwert . the dump site i didnt know thank you , my comment was a suggestion  for @1337yokese to get full functionality of rdpwrapper with a windows server. you con use proxmox for the vms

**Comment by nattlip** [comment]
@sashaqwert . the dump site i didnt know thank you , my comment was a suggestion  for @1337yokese to get full functionality of rdpwrapper with a windows server. you con use proxmox for the vms
