### ISSUE TITLE
credentials dont work

### ISSUE THREAD

**Issue by MrDOntDIe** [stascorp/rdpwrap#2042]
I havnt used rdp wrapper in a while but i came back and i checked conf and everything is right but i canoot log in because it says my credentials are wrong

**Comment by sashaqwert** [comment]
Are you using custom credital provider ([multiOTP](https://github.com/multiOTP/multiOTPCredentialProvider), ...)? If true, please, uninstall this software and try again.

**Comment by MrDOntDIe** [comment]
how do i check if i have that?

**Comment by sashaqwert** [comment]
> how do i check if i have that?

If your login process to Windows (locally and/or via RDP) differs from the one originally included in Windows, then you have similar software. Otherwise, 99% of the fact that such software is not installed.

It is recommended to use local accounts to test RDP Wrapeer. If you have a Microsoft account, then try `MicrosoftAccount\email` as your username (For example, `MicrosoftAccount\test@example.com`)

**Comment by sashaqwert** [comment]
Authentification problems is not a RDP Wrapper issue. Closed as solved.
