### ISSUE TITLE
Blue screen on Windows 7 Professional

### ISSUE THREAD

**Issue by mrsilver76** [stascorp/rdpwrap#205]
Great piece of software! It allows me to tinker with the HTPC whilst the other half is watching something on TV. 

However I'm occasionally getting blue screens and it's pointing to this wrapper. Is there a log file somewhere I can take a look at to see more details about what the problem might be?

I've looked in Program Data and App Data and cannot find anything.

**Comment by binarymaster** [comment]
First of all, please take a photo of BSoD to prove its relation to the RDP Wrapper.

RDP Wrapper works in user mode and doesn't use any kernel mode drivers, so in theory it just can not cause Blue Screen of Death.

**Comment by PieMistake** [comment]
I don't have a picture I can share I'm afraid, but I do have a screen grab from BlueScreenView:

![image](https://cloud.githubusercontent.com/assets/5740330/22712195/ccefff88-ed7b-11e6-83af-bea68bb0c333.png)

Any thoughts appreciated!

**Comment by mrsilver76** [comment]
I don't have a photo handy I'm afraid, but I do have this screen grab from BlueScreenView:

![image](https://cloud.githubusercontent.com/assets/5719686/22712501/e3dc3a26-ed7c-11e6-8925-a40071ab1b90.png)

Any thoughts appreciated!

**Comment by binarymaster** [comment]
Well, `rdpencdd.sys` driver file is not related to the RDP Wrapper, it is Microsoft's file.

So there's something other causing BSoD. Check whether the latest Windows Updates are installed, it might be important in your situation.

**Comment by mrsilver76** [comment]
True, it's a Microsoft file relating to RDP. I don't know if RDP Wrapper is triggering it or something else is going on - hence was wondering if RDP Wrapper wrote a log file anywhere that may help nail down the issue?

(I'm fully up to date on Windows Updates and virus scans)

**Comment by binarymaster** [comment]
You can create `rdpwrap.txt` log file in your system disk root directory (i.e. `C:\rdpwrap.txt`), it will log some debug information.

**Comment by mrsilver76** [comment]
Awesome, thanks!

**Comment by CollinChaffin** [comment]
I too confirm after installing rdpwrap and only immediately after installing on WIN7x86 Enterprise I am also getting a bluescreen literally every other rdp login.  I get one successful login per reboot, the 2nd causes bluescreen.  How can I generate the log you need to look into it?

**Comment by CollinChaffin** [comment]
Why was this closed?  Can you please tell us details on how to create you a debug log you referred to above?  This is reproducible and is literally a bluescreen after the 1st RDP session no matter what - and is starting to corrupt my machines because of this.  When RDP wrapper is removed and default single session admin rdp restored, never once is there any bluescreen.

I'm happy to help gather info and help track down the root cause but please re-open this issue until there is a resolution so we can all help work on it as I'm sure everyone else experiencing this also wants to help!  Thanks!

**Comment by binarymaster** [comment]
> Can you please tell us details on how to create you a debug log you referred to above?

Just create `rdpwrap.txt` in the root folder of your system drive, and restart Terminal Services.

**Comment by CollinChaffin** [comment]
Okay so now with a log in hand let me ask the million dollar question because I think I see a possible correlation here......I don't suppose the in-memory patching that this wrapper is doing holds through a S3 sleep and wake cycle?  The log only shows it initializing nothing else, but I just noticed I may have connected for the first time a couple times in a row......but before this HTPC ever did a S3 sleep and woke which is why I ask.

**Comment by CollinChaffin** [comment]
That and my last bluescreen logged the exact same init stuff but has only one additional line which does not offer much detail, but perhaps means something to you?:

 >>> SvchostPushServiceGlobals

**Comment by binarymaster** [comment]
Well... this is strange, try cleaning `rdpwrap.txt` log file and restart Terminal Services that way:

`RDPWInst.exe -r`

Then check log contents again.

**Comment by CollinChaffin** [comment]
It only logs the "typical" startup if that's what you were after?  Here is the init/restart:

Here first is what is in the CMD window showing restart status as a FYI:

![snag_7-4-2017_03-01-10](https://user-images.githubusercontent.com/9301483/27820725-4f9e090a-6065-11e7-9691-c036520367b2.png)


Followed by this in the rdpwrapper.txt log:

````
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x6DE90000
SvcMain:    termsrv.dll+0x15ED3
SvcGlobals: termsrv.dll+0xE162
Version:    6.1.7601.18637
Freezing threads...
Caching patch codes...
Hook SLGetWindowsInformationDWORD
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
Policy query: TerminalServices-RemoteConnectionManager-AllowRemoteConnections
Policy rewrite: 1
Policy query: TerminalServices-RemoteConnectionManager-AllowMultipleSessions
Policy rewrite: 1
Policy query: TerminalServices-RemoteConnectionManager-AllowAppServerMode
Policy rewrite: 1
Policy query: TerminalServices-RemoteConnectionManager-AllowMultimon
Policy rewrite: 1
Policy query: TerminalServices-RemoteConnectionManager-MaxUserSessions
Policy rewrite: 0
Policy query: TerminalServices-RemoteConnectionManager-45344fe7-00e6-4ac6-9f01-d01fd4ffadfb-MaxSessions
Policy rewrite: 2
Policy query: TerminalServices-RemoteConnectionManager-45344fe7-00e6-4ac6-9f01-d01fd4ffadfb-LocalOnly
Policy rewrite: 0
Policy query: TerminalServices-DeviceRedirection-Licenses-TSEasyPrintAllowed
Policy rewrite: 1
Policy query: TerminalServices-DeviceRedirection-Licenses-TSEasyPrintAllowed
Policy rewrite: 1
Policy query: TerminalServices-DeviceRedirection-Licenses-TSEasyPrintAllowed
Policy rewrite: 1
````

I am then able to attach without error.

However, here's why I'm leaning towards (at this point I'd bet the farm on this theory) the S3 deep sleep (or a potential specific sleep mode) affecting the in-memory patching - I just restarted this system (after yet another bluescreen) and have 2 different accounts connecting and randomly alternating between connecting from a single machine, to splitting their logins from 2 different pcs just to test - and I cannot make it bluescreen UNTIL THE SECOND I PUT IT INTO SLEEP AND RE-AWAKE IT and continue what I have been repeating successfully over and over.  The very FIRST connection AFTER a S3 deep sleep and awake is when it results in a bluescreen in my testing.   At the same time, if I leave the sleep mode config and everything else identical on this machine and only uninstall rdpwrapper and revert to still allowing RDP (invitations and single admin mode on the REMOTE tab of adv comp settings) I can then return to performing (albeit now SINGLE user) RDP connect/disconnect/reconnect and once again NEVER get a bluescreen.

Hopefully this helps clarify.  I know it does nothing to offer any insight as to WHY and since the rdpwrapper.txt only seems to be logging the initialization (which is always normal) and then the crash occurs at the very exact SECOND that the connection occurs it really makes me walk through in my mind that what "could" be happening here is that something in RAM gets reset upon sleep wakeup and NEVER SUBSEQUENTLY RE-PATCHED as it had been already AT INIT TIME......and because of that, there is a panic situation where the actual listener is the UN-PATCHED code trying to execute in what could be a hodge-podge RAM code vs actual dll situation.

Thoughts?  Do you have the ability to throw one of your machines into a deep s3 sleep and awake it then make a few new connections to see if you can reproduce?  I know here it is 100% reproducible using the above steps I've been using and again I can't get a single connection after wakeup without the bluescreen and on the flip side, can't make it fail if I never let it initially go to sleep to begin with.

**Comment by CollinChaffin** [comment]
FYI @binarymaster and any other contributing DEVS....I have not reproduced this on THREE additional WIN7x64 systems all with version 1.61.  Every single one bluescreens if I make a single connection to them after putting them to S3 sleep and awaking them first.  That's pretty glaring evidence not sure why more haven't complained I guess perhaps that many that run this wrapper are not using S3 sleep and instead hibernating or just shutting down - but those in this thread also certainly can't be the only ones, either.

Again to reproduce:  Take any x64 win7 (of ANY flavor), patch with rdpwrapper 1.61, reboot.  Make initial connection(s), repeat, heck make a few connections all from the same test host using different accounts - you will not see any failure.  Then, regardless of disconnecting any connections (because it simply disconnects upon sleep), place the host into S3 sleep (must first set the bios to S3 sleep to RAM - this is usually the default on newer systems).  Wait a few seconds and awake the system.  Make a single connection and just after you see the screen of the host (re)lock indicating it has accepted the login (but before you see the RDP window paint an initial screen) you will then generate a hard bluescreen 0F crash on the host.

I have the same systems with sleep turned off now, and have made dozens and dozens of connections using mult accounts and no crash on any as long as the S3 sleep does not occur at least once.  Once it does even once - all bets are off expect a bluescreen.  Hopefully this can be fixed to somehow either change the in-memory patching and maybe an area was just missed that will take care of this, or perhaps this is more serious and requires a whole different approach (like going back to physically patching dlls with each version).  Hopefully not the latter.

Hope all this testing has helped.
