### ISSUE TITLE
Windows 10.0.15063 Creative update

### ISSUE THREAD

**Issue by Moonage62** [stascorp/rdpwrap#235]
Ran the Creative update Microsoft is pushing.  Now RDPWrapper is not listening, fully supported.  Was working great before the update.

**Comment by mrlavalava** [comment]
It'll be an update to termserv.dll. The Creative Update lists a version number of 10.0.15063.0 for the file.

**Comment by Moonage62** [comment]
That is correct.  I'm uninstalling the upgrade.  Doesn't seem to bring
anything I need to the table.

**Comment by quicken2k** [comment]
Will this get fixed for the creators update?

**Comment by l33tissw00t** [comment]
See https://github.com/stascorp/rdpwrap/issues/194

**Comment by murrayv** [comment]
I upgraded Windows 10 Home to Pro Edition on 6 computers.
RDPWrap 1.6.1 w/updates works flawlessly.
A surprise benefit was much faster connection time.
I recommend upgrading to Pro.

**Comment by instinctualjealousy** [comment]
If they just offered RDP as a separate service, OR changed their draconian policy, perhaps I'd consider it.

Why is it that a Home machine can connect to a Pro machine? Why can a Home machine do RDP at all? If you're going to limit-by-SKU, it should be Pro-machine-can-connect-to-anything and Home-machine-can-connect-to-none.

You can't always decide what your client computer is going to be, either. Why penalize the Pro owner's ability to log into it based on what the CLIENT runs? And that's why RDPWrap exists. Let me remind everyone that a fresh Pro is $199. And the Home to Pro upgrade is $99. That's pretty crazy for *just* RDP. I don't use BitLocker, I don't use any of these host-side features. Especially on a laptop I use as a side-arm if anything.

That said, I can understand the people ranting and raving about this, this issue has been known since January thanks to the insider previews. At this rate, I wouldn't expect a fix for a damn year. Nothing against those contributing, nothing against those willing to test and go to the immense trouble this no doubt is causing. It just seems like it's a damned quandary, rarely are things stalled to this degree and it's worrying.

**Comment by macieks72** [comment]
After I updated Windows 10 to the Creators Update, rdpwrap not working. I can't connect. Please fix it.

**Comment by andrew-xdn** [comment]
Confirm the issue.

**Comment by guilegatan** [comment]
Same issue here after doing creators update.
Microsoft Windows [Version 10.0.15063]

**Comment by jaggeri** [comment]
Same problem here with creator version 1703.

RDPCHeck not listening anymore, loop back check failed.

Rolling back to previous version

**Comment by StarfighterJ** [comment]
Same After I updated Windows 10 to the Creators Update, rdpwrap not working. I can't connect. Please fix it. FYI I think also if you Roll back your still going to be forced with Creators Edition 1703 eventually.

**Comment by StarfighterJ** [comment]
Same issue here after doing creators update.
Microsoft Windows [Version 10.0.15063]
Rolling back to 1607 is not probably not a good Idea cause eventually your going to be stuck with 1703 Like me My windows.old is now gone

**Comment by whatdoesdfoxsay** [comment]
So, just an update for any interested parties -

I recently installed the Creator's Update, which broke rdpwrap for me on W10. Due to several other issues (broken start menu/task bar, etc) that the in-place upgrade caused, I opted to completely format my drive and install W10 from scratch using the Windows USB Media Creation Tool. The version that it installed was the most recent version (1703) Build 15063.332.

After this process, I installed rdpwrap (for the first time on this Windows install) and everything works perfectly. I hypothesize that something changed during the in-place upgrade to Creator's Update caused the issue everyone is experiencing. Hopefully this helps ya'll out as well!

**Comment by sskras** [comment]
Wow @foxngit , that's very interesting.  One (with enough time) could recreate both OS states from the scratch + then compare files and registry branches on both OS images.

What is the latest Build before Creators's Update which an installed from an .iso image, anyone?

**Comment by comtechnet** [comment]
I tested a setup with 1703 and yes rdpwrap stopped working.  But - all I had to do, in my case was simply run the rdpwrap install.bat file again - and it started working again.  However, the little rdp monitor program gives a not authorized error for each of the three users I tried - all were admins of the machine of the three was a domain admin.   So - try just re-running the install.bat on 1703 and see if it works like it did for me (to clarify, under 1607, rdlwrap ran fine, including running the little rdp monitor utility, after 1703 rdlwrap did not work until i reran its install.bat, but the little rdp monitor utility requests a login, where all three of my logins got a not authorized blue screen)  I did this testing today.

**Comment by StarfighterJ** [comment]
Is it Windows Pro  or Home? because Pro Should work regardless

**Comment by comtechnet** [comment]
It's enterprise

**Comment by l33tissw00t** [comment]
Same idea as Pro as far as this is concerned.  Issue ONLY applies to Home.

**Comment by StarfighterJ** [comment]
I thought the whole Idea of RDPWrap was to Support Home editions Remote functions?

**Comment by StarfighterJ** [comment]
Is Anyone working the Fix To support Creators Home Edition?

**Comment by smartmanru** [comment]
tyy

**Comment by BKHawk** [comment]
![image](https://user-images.githubusercontent.com/30541145/28741245-36f0fce6-73cf-11e7-844d-b9f49c8c9bf7.png)

![image](https://user-images.githubusercontent.com/30541145/28741285-257f45c0-73d0-11e7-976a-c6c199510b72.png)

I have enjoyed using rdp but recently it has stopped working on both my Win 10 systems.

I have tried all the suggestions including uninstalling, reinstalling, and running update.bat but I still get "Not listening".  Are there any other suggestions binarymaster?

**Comment by Odeivo** [comment]
Curiously, my problem was that my internet provider has implemented without prior notice the IPv6 protocol, coinciding, in my case, with the installation of the version creator's Update. I made the necessary changes on my router and the listening status changed to listening. Now it works correctly, but I do not have concurrent sessions.
Check your ISP protocol.
Regards!

**Comment by nazghul2k** [comment]
Hi, Windows 10, Version 1703, Build 15063.674, Listener State: Not listening, can you fix it? Thx.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1381586/termsrv.zip)

**Comment by Moonage62** [comment]
Upgrading to Professional is the best fix.  Home edition does not support RDP.

**Comment by nazghul2k** [comment]
I think windows server is the best solution... but

**Comment by binarymaster** [comment]
@nazghul2k read the README first before posting.

**Comment by nazghul2k** [comment]
I know my version is not supported. My question was: can you fix it. Now i know you cant fix cuz it not supported. So i refrase: can you make rdpwrap to support 15063.674?

**Comment by binarymaster** [comment]
@nazghul2k provide diagnostics (RDPConf) screenshot to ensure your termsrv build version.

**Comment by nazghul2k** [comment]
Done.
![rdp](https://user-images.githubusercontent.com/32760834/31545095-99a8d58c-b026-11e7-9035-fca8ecd7661e.jpg)

**Comment by binarymaster** [comment]
Read the **Known Issues** section in README again, your issue is listed.

**Comment by nazghul2k** [comment]
Reading rules! All hails Binarymaster the Great! =)
Problem solved.
