### ISSUE TITLE
RDPWrap-v 1.6.1  Stoped wroking after Windows 10 Creatore Edition 1703

### ISSUE THREAD

**Issue by StarfighterJ** [stascorp/rdpwrap#256]
RDPWrap-v 1.6.1  Stoped wroking after Windows 10 Creatore Edition 1703. I hope a new Release I coming out soon.

**Comment by hxpq13** [comment]
Same here. After executing test the remote connection establishes. But when you try to Log in it says something like "You can not login with this user account, because of some restrictions..."  (smthing like that. I use a different language). After approx 30 sec the Connection crashes.

Hope that a new release will come soon!

P.S.: I case noone told you yet:simply awsome!!! THX!

**Comment by MortenGuldager** [comment]
see https://github.com/stascorp/rdpwrap/issues/194
