### ISSUE TITLE
It dosen't work when windows 10 update

### ISSUE THREAD

**Issue by HenrySiuXiao** [stascorp/rdpwrap#299]
It worked well before. Today Windows 10 update to 15063.540, RDP Wrap don't work immediately.
When I run RDPConf.exe, Listener state is “Not listening”. 
Is there any way to solve the problem?

**Comment by LufyCZ** [comment]
Duplicate

**Comment by mccorkle** [comment]
Check out the solution provided by @youjoy  in #194

**Comment by NA6T** [comment]
I had the same problem after a Window 10 update.  Before, everything was working with 3 connections working all the time... After the update and windows 10 rebooting only was connection was available with the 'not responding ' message.  I re-installed RDPWrap (not uninstalling the first install) and everything started  working correctly with 3 connections working all the time... Good ol MS and their updates.....  RDP WRAP is a great program and it sure makes it easy for 3 people to use a Win10 pro desktop as a small server .   That's why I wanted to post this for everyone to see.... thanks, Bob

**Comment by mccorkle** [comment]
Please see issue #194 for resolution.
