### ISSUE TITLE
Unknown code 0x1104

### ISSUE THREAD

**Issue by nerijus** [stascorp/rdpwrap#363]
I installed succesfully on the latest Windows 10 Home (copied 64 bit rfxvmt.dll to system32), but when trying RDPCheck I get:
Disconnected
Unknown code 0x1104

With Remote Desktop Connection I get:
Because of a protocol error detected at the client (code 0x1104), this session will be disconnected.

Tried to change Authentication Mode in RDPConf, didn't help.

The PC has 2 network cards.

**Comment by binarymaster** [comment]
This is not RDP Wrapper issue, see these links:
- https://social.technet.microsoft.com/Forums/windows/en-US/b034c9b9-fb3e-4872-9ba8-58499bab4ada/because-of-a-protocol-error-detected-at-the-client-code-0x1104?forum=winserverTS
- https://serverfault.com/questions/224950/windows-remote-desktop-protocol-error
