### ISSUE TITLE
W8.1 ver-6.3.9600.18928

### ISSUE THREAD

**Issue by vgisbert** [stascorp/rdpwrap#420]
RDPwrap is V1.6.2 says not supported, I attached the sample.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1768883/termsrv.zip)

**Comment by KipFun** [comment]
build 9600.18931 not supported to

[termsrv_9600.18931.zip](https://github.com/stascorp/rdpwrap/files/1770191/termsrv_9600.18931.zip)

**Comment by binarymaster** [comment]
Duplicate of #418.

@KipFun different versions should be in different issues.

**Comment by ralphys** [comment]
Is it there an ETA to add support for ver-6.3.9600.18928?

I ran Windows Updates (something I shouldn't have done!!) and I haven't been able to use the wrapper ever since. To top it off, I do not have a restore point to go back so I'm pretty much stuck waiting for an update :( 

Between, thank you @binarymaster for your hard work. Your wrapper has been extremely useful!

**Comment by cubedj** [comment]
the termsrv.dll hasn't been changed in the build 6.3.9600.18931 so it's still 6.3.9600.18928... so it is the same problem... sort of... ;)

**Comment by ralphys** [comment]
@cubedj what I did to mitigate the problem in the mean time was to get the termsrv.dll from a previous backup and replace the one installed (ver-6.3.9600.18928) with it. So I got my multi-session back at least for now.
