### ISSUE TITLE
Cannot use RDP Wrapper with multiple users

### ISSUE THREAD

**Issue by hudway** [stascorp/rdpwrap#458]
Will not allow multiple users. Acts as if there is no RDP Wrapper Installed, no indication of problem in config.
![rdpwrapper 4-26 18](https://user-images.githubusercontent.com/15970455/39333634-d0706874-4968-11e8-9df2-8c8e23105282.PNG)

**Comment by tvcat** [comment]
Try "GUI Authentication only"

**Comment by arniva48** [comment]
![rdpp](https://user-images.githubusercontent.com/39023592/39671881-4d855f0a-5129-11e8-950c-b1d4c98b53be.png)


windows update. rdp stop help

**Comment by fragtion** [comment]
@hudway : Suggestion offered by @tvcat should solve this known issue (see #422)

@arniva48 : That is separate known issue (see #456)

**Comment by binarymaster** [comment]
@hudway are you using the same user account to log in multiple times?

**Comment by HighStar01a** [comment]
I got the same issue.  A workaround is don't install RDP wrapper with the same account you want to remote in with.  For whatever reason, you can't RDP in with the same account used to install it.

I used the Administrator account to install, then RDP with the account I normally use.

Open CMD with User:".\Administrator"
CD to location of Download
Uninstall.bat
Install.bat
Run RDP Checker with User:".\Administrator"
RDP account is your normal account (Not currently logged in user).

**Comment by binarymaster** [comment]
Closing as inactive.

**Comment by maravento** [comment]
Why do you close this issue if the problem has not been fixed?

**Comment by guebert** [comment]
I had the same problem. The problem was the INI-file. Even everything seems ok (as in the initital posting) it did not work. I used a pre-configured INI from a foreign site.

https://github.com/stascorp/rdpwrap/issues/1054

I took the original INI from here

https://github.com/stascorp/rdpwrap/tree/master/res

added the needed sections for my Win release

https://www.andysblog.de/windows-probleme-beim-rdp-wrapper-loesen

then it worked!
