### ISSUE TITLE
disabled "Single session per user" not working

### ISSUE THREAD

**Issue by lolvince** [stascorp/rdpwrap#513]
hello, 

I understand that multiple sessions were no longer functional on the Win 10 Pro version.
is there a solution ?
is older version of windows 10 pro compatible?

Thanks for your help

![image](https://user-images.githubusercontent.com/24383570/42023558-6f8d20c2-7ac0-11e8-8c59-7824ed4019e3.png)

**Comment by lolvince** [comment]
same problem here # 358

**Comment by lolvince** [comment]
for information, the KB4284848 add great patch for remote desktop ;)

**Comment by josh900** [comment]
did the update fix the issue for you?

**Comment by lolvince** [comment]
I did not test on the server part, but the patch on the client avoids display anomalies related to the right clicks

**Comment by josh900** [comment]
Didn't change the situation for me.. Though, yes, good to hear about that fix.

**Comment by Jefrejtor** [comment]
Would be nice to have a fix for this, as a Windows reinstall is not an option for me currently. It's really weird because it used to work for me a couple days ago, but today it just stoppped. Multiple accounts are still fine.

**Comment by vandenk** [comment]
Same strange problem here with Win10 1803 ....

Let me explain :
The console session is open with the administrator account (there is another account "Erik" with administrator rights on this PC).
If I open a 2nd session with the Administrator account using RDPCheck.exe everything is OK.
Also if I open 2 sessions with Erik account using RDPCheck.exe everything is OK:
![rdpcheck](https://user-images.githubusercontent.com/11425010/43192765-8b349b40-8ffe-11e8-9dd3-a44bc8fca8a6.jpg)

On the other hand if I use the remote desktop connexion (Windows) from another PC=PC2 with the Administrator account it closes the console session on PC1 (which I get on the PC2) !
If I re-open a remote desktop connection with the Administrator account (from PC2): the first session closes !
But if I reopen a console session (on PC1) with the Administrator account it opens me a new Administrator session ... very weird.
Now even more strange if I re-open a remote office conexion (from PC2) with the Administrator account: it works !!!
If I use remote desktop conexion (Windows) from PC2 with Erik account to open 2 sessions it does not work (the first session is closed).
On the other hand if I open a local session (console) with the account Erik on the PC1 and I reouvre a remote desktop connection (since the PC2) with the account Erik: it works !!!
![bureau network2](https://user-images.githubusercontent.com/11425010/43193080-5f101ec6-8fff-11e8-8674-982172a9ffce.jpg)

If I check (with RDPConf.exe) "GUI Authentication Only" instead of "Network Level Authentication".
I have the same problem as before with the Administrator account: it closes the console session (which I get on the PC2).
By cons I can open multiple remote desktop session with Erik account (without local session (console) with Erik account open on PC1)) ...

**Comment by vandenk** [comment]
But the strangest and when I use the remote desktop connection locally (127.0.0.2 to 127.0.0.254).

I open a console session with the administrator account, since this session I start the remote desktop connection and try to log in with the administrator account:
it opens another local session (console) Administrator !!! I never saw that !!!

**Comment by sebaxakerhtc** [comment]
Closed as not actual
