### ISSUE TITLE
Windows 10 home - Says invalid username/password

### ISSUE THREAD

**Issue by Kannkor** [stascorp/rdpwrap#651]
I just installed rdpwrapper.
I have the config open and it says:
Wrapper state: Installed
Service State: running
Listener state: Listening

Version: 10.0.17134.1
[fully supported]

I've tried various checkboxes, at this very moment, I have it set to:
Enable remote desktop on port 3389
No other checkboxes checked here

Auth mode: I've tried all 3
Session shadowing mode: Full access with user's permission (not changed as I'm not trying to use this, I do not believe).

I've used RDPCheck.exe, and enter my username/password, and it works. It loads a new window and appears to work fine. It's resolution is very small (which I've read is intended as it's just a tester, just confirming that I do believe rdpcheck is working).

Full disclosure: 
Windows 10 Home
The computer is logged in as the main account/administrator
I am currently using teamviewer on that computer to install rdpwrapper/test/make changes

From my remote pc, I am using windows Remote Desktop Connection
I enter in the IP of the windows 10 home machine
It comes up with a windows server 2008 login screen. I enter my username/password in, and it says invalid user name and password. I've tried this at least 10 times, and can confirm I have the right password (as I can log into the web, and I used the same in RDPCheck).

On the windows 10 home machine, I can confirm the allow remote connections is checked.

I'm assuming I am just missing something, but I've looked back through the readme.md and can't seem to figure it out.

Does anyone have any suggestions? Or is there more information I can provide to assist?
Thanks

**Comment by Igoricius** [comment]
Hi @Kannkor, it is little bit confusing when you mention win server 2008 login screen. You are connecting to Win 10 machine? Are you trying to connect with remote user of Win 10 machine? Check these settings of destination machine:

![image](https://user-images.githubusercontent.com/47040465/52174897-13f8d700-279b-11e9-9608-432bdd78c616.png)

**Comment by MadDog927ca** [comment]
> Hi @Kannkor, it is little bit confusing when you mention win server 2008 login screen. You are connecting to Win 10 machine? Are you trying to connect with remote user of Win 10 machine? Check these settings of destination machine:
> 
Hi @Kannkor - Windows 10 Home doesn't have the 'Remote Desktop' section on the System Properties 'Remote' tab, even with RDP Wrapper installed.

@Igoricius - I suspect you're trying to log in with a local account that isn't a member of the local 'Administrators' group, which is why it works with Team Viewer as a console connection and not via RDP. That's because they're not a member of a hidden group called 'Remote Desktop Users'.
https://github.com/stascorp/rdpwrap/issues/107#issuecomment-216041697
You'll need to create this special group following the instructions in the article above, and then add your non-admin user to the group.
If your user is an admin user, you haven't completely set up RDP Wrapper for Windows 10 Home and will have to do some more reading.

**Comment by binarymaster** [comment]
> I enter in the IP of the windows 10 home machine
It comes up with a windows server 2008 login screen. I enter my username/password in, and it says invalid user name and password.

Misconfiguration on your router side (port forwarding), fix it yourself.
