### ISSUE TITLE
New builds?

### ISSUE THREAD

**Issue by joebrug** [stascorp/rdpwrap#661]
Hello, @binarymaster.. I tried to follow the youtube video to add new builds to the .ini file but was very confused. I would love to be able to handle it myself to take the burden off of you :( Do you have any plans to add current termserv.dll builds to the ini file or is this project considered dead?

Thank you

**Comment by CypherAus** [comment]
For now see https://github.com/stascorp/rdpwrap/issues/645 for the latest ini file for latest Win 10 production

**Comment by joebrug** [comment]
Hi @CypherAus , thanks, but mainly concerned about windows 7 February security updates. I haven't seen any info on that. It broke with last months "preview" updates.

**Comment by binarymaster** [comment]
@joebrug currently I don't have time to maintain this project, because I'm busy with other projects.

New builds are added to INI file by other members of the community in [appropriate issues](https://github.com/stascorp/rdpwrap/issues?q=is%3Aissue+is%3Aopen+label%3A%22add+build%22), but are not verified by me.

**Comment by joebrug** [comment]
Thanks @binarymaster , I understand being busy. Hopefully someone else will create ini entries for the rest of us. If possible, and you manage to find the time, maybe an updated/clear youtube tutorial on how to find proper settings, so we can stop bugging you :) Had trouble following the existing video.
