### ISSUE TITLE
Creating multiple sessions

### ISSUE THREAD

**Issue by pmsharp2** [stascorp/rdpwrap#801]
After a recent windows update I've found that rdpwrap is connecting users with multiple sessions despite the "Single sessions per users" option being enabled. Not sure how to troubleshoot this. Picture of sessions and config bellow.
Looking at the image, the middle user is user 2
![Capture](https://user-images.githubusercontent.com/29620685/58510191-d65ef600-815d-11e9-9ee9-49bdee4b9276.PNG)

**Comment by yesidtaz** [comment]
Hello good day friend that option is to activate a single connection per user, example if you have a user named Andres to be enabled allows you to only enter with that account 1 session only, if you deactivate you will be able to create two sessions with the same account called Andres ... said this is called multisession per user but it is not multiuser which is what we use RDP for.

**Comment by AzraelNewtype** [comment]
No, I don't think you understand. Prior to the update, one could log in at the machine physically, then walk away and log into the same session remotely. Ever since, if you attempt to log into a machine that had an active session locally at any point (whether it started as a remote session or not), an error occurs and we get a second session with the same account. In essence, it is behaving exactly as if "Single session per user" was _unchecked_, which I can verify from using it that way some time ago. In case it's not clear (as I'm not the original poster), I'm having the same issue.

I'm not entirely sure why this started happening, but I tend to launch the viewer from a linux command line, so I have the relevant error code:

`[00:30:29:395] [14141:14142] [INFO][com.freerdp.client.x11] - Logon Error Info LOGON_FAILED_UPDATE_PASSWORD [LOGON_MSG_SESSION_CONTINUE]
`
Just to be clear, despite what the error message looks like, this wasn't caused by an incorrect password. I start the server from a script that has the password saved, and windows did actually let me in after all, just not to the session I wanted. I haven't been able to find any documentation as to what's actually happening though, just what isn't.

**Comment by asmtron** [comment]
please try the new [rdpwrap_ini_updater_(07_June_2019).zip](https://github.com/stascorp/rdpwrap/issues/795#issue-448382061) with fixed **10.0.17763.437 x64**

**Comment by pmsharp2** [comment]
What @AzraelNewtype said is the same thing I'm experiencing.
Thanks @asmtron I will give the new ini updater a try and see if the issue persists.

**Comment by pmsharp2** [comment]
Nice work the new ini does appear to resolve the issue. Thank you for your great work.
