### ISSUE TITLE
Status of this repository

### ISSUE THREAD

**Issue by alehaa** [stascorp/rdpwrap#815]
At the moment a lot of issues are open and before using RDPwrap with a recent version of windows, one needs to download an ini from one of the issues to get the wrapper working.

Therefore, I'm wondering if this project is still being maintained, or if there's a maintained fork of this project. Maybe one could even assist in this project as maintainer?

**Comment by dlh2** [comment]
I've been searching for an issue like this on all these 567 issues.

At the moment, I'm looking that the only maintainer is @sebaxakerhtc because I see on the Closing Issues that after 18 pages is all about him closing and closing, but for some reason he might not be able to commit the changes onto the respository itself.

We might ask to @binarymaster to add this dude as contributor or forward this respository to his repository because this is not being maintained anymore by the original creator.

**Comment by sebaxakerhtc** [comment]
> he might not be able to commit the changes onto the respository itself

That's true.
But Original creator will back to project

**Comment by sebaxakerhtc** [comment]
> if there's a maintained fork of this project.

https://github.com/sebaxakerhtc/rdpwrap
