### ISSUE TITLE
Request for support 10.0.17763.771

### ISSUE THREAD

**Issue by Magissia** [stascorp/rdpwrap#969]
Connecting remotely disconnects the local user.
Attached dll file.
Ini file date 2019-09-02
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4091872/termsrv.zip)

**Comment by Magissia** [comment]
Looks like https://raw.githubusercontent.com/asmtron/rdpwrap/01c887bb42d80730e671a897fd45ee87ff90a981/res/rdpwrap.ini works

**Comment by modzilla99** [comment]
Are you running LTSC2019? Since it doesn't seem to work here:

![Screenshot](https://user-images.githubusercontent.com/32171364/73359554-5fa46a80-42a1-11ea-94f3-4f16dde2ecd3.png)

EDIT: Alright I think my termsrv is coruppted

EDIT2: I restored the teamsrv.dll with sfc /scannow and dism, but after Installation it's still not working. RDPcheck throws out the same error and when I try to connect with a different account it wants to log me out like normal...
